spring:
  thymeleaf:
    cache: false
    mode: html
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/baseteste?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root